# Generated by Django 5.2.7 on 2025-10-22 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('food', 'Food Services'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('other', 'Other')], max_length=20)),
                ('hall', models.CharField(choices=[('aftab', 'Aftab Hall'), ('ambedkar', 'Dr. B.R. Ambedkar Hall'), ('hadi-hasan', 'Hadi Hasan Hall'), ('mohsinul-mulk', 'Mohsinul Mulk Hall'), ('mohd-habib', 'Mohd. Habib Hall'), ('nadeem-tarin', 'Nadeem Tarin Hall'), ('ross-masood', 'Ross Masood Hall'), ('sir-shah-sulaiman', 'Sir Shah Sulaiman Hall'), ('sir-syed-north', 'Sir Syed Hall (North)'), ('sir-syed-south', 'Sir Syed Hall (South)'), ('sir-ziauddin', 'Sir Ziauddin Hall'), ('viqarul-mulk', 'Viqarul Mulk Hall'), ('abdullah', 'Abdullah Hall'), ('bibi-fatima', 'Bibi Fatima Hall'), ('begum-sultan-jahan', 'Begum Sultan Jahan Hall'), ('begum-azeezun-nisa', 'Begum Azeezun Nisa Hall'), ('indira-gandhi', 'Indira Gandhi Hall'), ('sarojini-naidu', 'Sarojini Naidu Hall'), ('nrsc', "Non-Resident Students' Centre (NRSC)")], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
