# Generated by Django 4.1.13 on 2025-10-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(choices=[('staff', 'Staff/General'), ('provost', 'Provost/Hall Management'), ('dsw', 'DSW/Student Welfare'), ('exam_controller', 'Exam Controller')], default='staff', max_length=20),
        ),
    ]
