# Generated by Django 4.1.13 on 2025-10-25 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_complaint_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('application_type', models.CharField(choices=[('room-change', 'Room Change Request'), ('library-subscription', 'Library Subscription'), ('exam-revaluation', 'Exam Re-evaluation'), ('fee-concession', 'Fee Concession'), ('other', 'Other')], max_length=20)),
                ('department', models.CharField(choices=[('dsw', 'Dean of Student Welfare'), ('library', 'Library'), ('examination', 'Examination Controller'), ('accounts', 'Accounts')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
