# Generated by Django 5.2.7 on 2025-10-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_first_name_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('provost', 'Provost'), ('dsw', 'DSW'), ('exam_controller', 'Exam Controller')], default='student', max_length=20),
        ),
    ]
