# Generated by Django 4.1.13 on 2025-10-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_application_department_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
