# Generated by Django 3.2.25 on 2025-10-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_application_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='department',
            field=models.CharField(choices=[('dsw', 'Dean of Student Welfare'), ('provost', 'Provost/Hall Management'), ('library', 'Library'), ('examination', 'Examination Controller'), ('dean', 'Dean Academics')], max_length=20),
        ),
    ]
